{% set name = "jupyter_server_fileid" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7486bca3acf9bbaab7ce5127f9f64d2df58f5d2de377609fb833291a7217a6a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-fileid = jupyter_server_fileid.cli:main

requirements:
  host:
    - hatchling >=1.0
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jupyter_server >=1.15,<3
    - jupyter_events >=0.5.0

test:
  imports:
    - jupyter_server_fileid
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter_server_fileid
  summary: A Jupyter Server extension providing an implementation of the File ID service.
  description: |
    A Jupyter Server extension providing an implementation of the File ID service.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
    - dlqqq
    - fcollonval
