{% set name = "jupyter_server_fileid" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffb11460ca5f8567644f6120b25613fca8e3f3048b38d14c6e3fe1902f314a9b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-fileid = jupyter_server_fileid.cli:main

requirements:
  host:
    - hatchling >=1.0
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_server >=1.15,<3
    - jupyter_events >=0.5.0

test:
  imports:
    - jupyter_server_fileid
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter_server_fileid
  summary: A Jupyter Server extension providing an implementation of the File ID service.
  description: |
    A Jupyter Server extension providing an implementation of the File ID service.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
    - dlqqq
    - fcollonval
